// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnGmNmEIPi4L_zG3gWGfYiU1UZf64nj8',
    appId: '1:774553141725:web:cffd895df3b9501fd3b634',
    messagingSenderId: '774553141725',
    projectId: 'classfury0',
    authDomain: 'classfury0.firebaseapp.com',
    storageBucket: 'classfury0.firebasestorage.app',
    measurementId: 'G-LWX366R651',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_b-sjR0Vb5M_1ttnocHb_o2bu6BF0aI',
    appId: '1:774553141725:android:c5c1d39de1a1f5e7d3b634',
    messagingSenderId: '774553141725',
    projectId: 'classfury0',
    storageBucket: 'classfury0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpJtYh2NJDTQsc_IdmPdmWEQOEAKmZRg',
    appId: '1:774553141725:ios:61eafeef382a9f6bd3b634',
    messagingSenderId: '774553141725',
    projectId: 'classfury0',
    storageBucket: 'classfury0.firebasestorage.app',
    iosBundleId: 'com.classfury.classfury',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpJtYh2NJDTQsc_IdmPdmWEQOEAKmZRg',
    appId: '1:774553141725:ios:dbd5612877e3432cd3b634',
    messagingSenderId: '774553141725',
    projectId: 'classfury0',
    storageBucket: 'classfury0.firebasestorage.app',
    iosBundleId: 'com.classfury.classfury',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnGmNmEIPi4L_zG3gWGfYiU1UZf64nj8',
    appId: '1:774553141725:web:0f7cafdf429af5dbd3b634',
    messagingSenderId: '774553141725',
    projectId: 'classfury0',
    authDomain: 'classfury0.firebaseapp.com',
    storageBucket: 'classfury0.firebasestorage.app',
    measurementId: 'G-EMJ52L2V9H',
  );
}
